### ISSUE TITLE
Deployment fails due to Virtual Machine image version  

### ISSUE THREAD

**Issue by mauricio-msft** [microsoft/r-server-hospital-length-of-stay#16]
The template **dsvm_arm** is using **"version": "18.02.00"** which is not available anymore or my subscription type doesn't support it.My Subscription is Visual Studio Enterprise.

Running **Get-AzVMImage** -Location "West US" -PublisherName "microsoft-ads" -Offer "windows-data-science-vm" -Skus "windows2016" I get all available images versions and 18.02.00 is not listed.

I was able to deploy successfully using version **03.25.19**

Please check it so the documentation can be updated.

**Comment by robertmcdaniel** [comment]
Hey Mauricio, what did you change to make it work with 3.25.19?  I did not see the option to change this setting in the template when deploying.  Did you manually download the template and make the change and redeploy from your private GitHub?

**Comment by mauricio-msft** [comment]
Hey Robert, that is exactly what I did, downloaded the template, made the change and redeployed from my private GitHub.
